# Konfiguracja aplikacji
spring.application.name=bybit-claude-bot

# Konfiguracja API Bybit
bybit.api.url=https://api.bybit.com
bybit.api.key=${BYBIT_API_KEY:your-api-key}
bybit.api.secret=${BYBIT_API_SECRET:your-api-secret}

# Konfiguracja API Claude
claude.api.url=https://api.anthropic.com/v1/messages
#api key claudi
claude.api.key=xxxxxxxxxxxx 
claude.api.version=2023-06-01
claude.api.model=claude-3-7-sonnet-20250219

# Konfiguracja tradingu
trading.symbol=ETHUSDC
trading.category=spot
trading.order.type=Market
trading.amount=0.001
# Interwa? w milisekundach (10000 = 10 sekund)
trading.interval.milliseconds=10000
# Tryb demo (true = bez rzeczywistych transakcji)
trading.demo=true

# Konfiguracja logowania
logging.level.root=INFO
logging.level.com.example.bybitbotai=DEBUG
# W??czenie kolorowania w konsoli
spring.output.ansi.enabled=ALWAYS

# Format logowania z kolorami
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n



# Konfiguracja serwera (opcjonalnie, je?li chcesz doda? API REST)
server.port=8080